import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional
from rich.console import Console

console = Console()

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}

SEVERITY_CVSS = {
    "critical": 9.5,
    "high":     7.5,
    "medium":   5.0,
    "low":      3.1,
    "info":     0.0,
}

SEVERITY_BADGE = {
    "critical": "![critical](https://img.shields.io/badge/severity-critical-darkred)",
    "high":     "![high](https://img.shields.io/badge/severity-high-red)",
    "medium":   "![medium](https://img.shields.io/badge/severity-medium-orange)",
    "low":      "![low](https://img.shields.io/badge/severity-low-yellow)",
    "info":     "![info](https://img.shields.io/badge/severity-info-blue)",
}


def _as_dict(session: Any) -> dict:
    if hasattr(session, "to_dict"):
        return session.to_dict()
    if isinstance(session, dict):
        return session
    return {}


def _findings(data: dict) -> list[dict]:
    items = data.get("findings_detail") or data.get("findings") or []
    if isinstance(items, dict):
        items = items.get("detail", [])
    return [f for f in items if isinstance(f, dict)]


def _anchor(text: str) -> str:
    slug = re.sub(r"[^\w\s-]", "", text.lower()).strip()
    return re.sub(r"[\s]+", "-", slug)


def _counts(findings: list[dict]) -> dict:
    counts = {k: 0 for k in SEVERITY_ORDER}
    for f in findings:
        sev = f.get("severity", "info")
        if sev in counts:
            counts[sev] += 1
    return counts


def _render(data: dict) -> str:
    findings = sorted(
        _findings(data),
        key=lambda f: SEVERITY_ORDER.get(f.get("severity", "info"), 5),
    )
    target = data.get("target", "unknown")
    counts = _counts(findings)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append(f"# Security Assessment Report — {target}")
    lines.append("")
    lines.append(f"> Generated by Prothos on {generated}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in SEVERITY_ORDER:
        lines.append(f"| {sev.capitalize()} | {counts[sev]} |")
    lines.append(f"| **Total** | **{len(findings)}** |")
    lines.append("")

    if data.get("started_at"):
        lines.append(f"- Session: `{data.get('session_id', '-')}`")
        lines.append(f"- Started: {data.get('started_at')}")
        lines.append(f"- Finished: {data.get('finished_at', '-')}")
        if data.get("duration_s") is not None:
            lines.append(f"- Duration: {data.get('duration_s')}s")
        lines.append("")

    lines.append("## Table of Contents")
    lines.append("")
    for i, f in enumerate(findings, 1):
        title = f.get("title") or f.get("issue") or f.get("module", "finding")
        sev = f.get("severity", "info")
        anchor = _anchor(f"{i}-{sev}-{title}")
        lines.append(f"{i}. [{title} ({sev})](#{anchor})")
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    for i, f in enumerate(findings, 1):
        title = f.get("title") or f.get("issue") or f.get("module", "finding")
        sev = f.get("severity", "info")
        anchor = _anchor(f"{i}-{sev}-{title}")
        lines.append(f"### <a name=\"{anchor}\"></a>{i}. {title}")
        lines.append("")
        lines.append(SEVERITY_BADGE.get(sev, ""))
        lines.append("")
        lines.append(f"- **Severity:** {sev}")
        lines.append(f"- **CVSS (estimated):** {SEVERITY_CVSS.get(sev, 0.0)}")
        lines.append(f"- **Module:** `{f.get('module', '-')}`")
        lines.append(f"- **Category:** {f.get('category', '-')}")
        if f.get("cve"):
            lines.append(f"- **CVE:** {f.get('cve')}")
        url = f.get("url") or f.get("target")
        if url:
            lines.append(f"- **Location:** `{url}`")
        if f.get("param"):
            lines.append(f"- **Parameter:** `{f.get('param')}`")
        lines.append("")
        if f.get("description"):
            lines.append("**Description**")
            lines.append("")
            lines.append(str(f.get("description")))
            lines.append("")
        if f.get("payload"):
            lines.append("**Proof of Concept**")
            lines.append("")
            lines.append("```")
            lines.append(str(f.get("payload")))
            lines.append("```")
            lines.append("")
        if f.get("evidence"):
            lines.append("**Evidence**")
            lines.append("")
            lines.append("```")
            lines.append(str(f.get("evidence"))[:2000])
            lines.append("```")
            lines.append("")
        lines.append("**Remediation**")
        lines.append("")
        lines.append(str(f.get("remediation") or "Review and remediate according to vendor guidance and OWASP recommendations."))
        lines.append("")
        lines.append("---")
        lines.append("")

    errors = data.get("errors") or []
    if errors:
        lines.append("## Errors / Notes")
        lines.append("")
        for e in errors:
            lines.append(f"- {e}")
        lines.append("")

    return "\n".join(lines)


def run_markdown_report(session: Any, output_path: str) -> str:
    data = _as_dict(session)
    findings = _findings(data)
    console.print(f"\n[bold red][*][/bold red] Markdown report → [bold white]{output_path}[/bold white]")
    console.print(f"[dim]    Findings: {len(findings)}[/dim]")

    content = _render(data)
    try:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        console.print(f"[dim][+] Saved to {output_path} ({len(content) // 1024}KB)[/dim]")
    except OSError as e:
        console.print(f"[red][!] Failed to save: {e}[/red]")

    return output_path
