from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from rich.console import Console

console = Console()

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}

SEVERITY_HEX = {
    "critical": "#8B0000",
    "high":     "#D32F2F",
    "medium":   "#F57C00",
    "low":      "#FBC02D",
    "info":     "#1976D2",
}

SEVERITY_CVSS = {
    "critical": 9.5, "high": 7.5, "medium": 5.0, "low": 3.1, "info": 0.0,
}

REMEDIATION_ROADMAP = {
    "critical": "Immediate: remediate within 24-48h, restrict exposure, rotate affected secrets.",
    "high":     "Short term: remediate within 1 week, add monitoring/WAF rules.",
    "medium":   "Planned: remediate within the current sprint/cycle.",
    "low":      "Backlog: address during routine maintenance.",
    "info":     "Informational: review for defense-in-depth.",
}


def _as_dict(session: Any) -> dict:
    if hasattr(session, "to_dict"):
        return session.to_dict()
    if isinstance(session, dict):
        return session
    return {}


def _findings(data: dict) -> list[dict]:
    items = data.get("findings_detail") or data.get("findings") or []
    return [f for f in items if isinstance(f, dict)]


def _counts(findings: list[dict]) -> dict:
    counts = {k: 0 for k in SEVERITY_ORDER}
    for f in findings:
        sev = f.get("severity", "info")
        if sev in counts:
            counts[sev] += 1
    return counts


def _build_pdf(data: dict, output_path: str, tester: str) -> bool:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
        )
        from reportlab.lib.enums import TA_CENTER
    except ImportError:
        return False

    findings = sorted(
        _findings(data),
        key=lambda f: SEVERITY_ORDER.get(f.get("severity", "info"), 5),
    )
    target = data.get("target", "unknown")
    counts = _counts(findings)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="Cover", fontSize=28, leading=34, alignment=TA_CENTER, spaceAfter=20))
    styles.add(ParagraphStyle(name="CoverSub", fontSize=14, leading=18, alignment=TA_CENTER, textColor=colors.grey))
    styles.add(ParagraphStyle(name="FindingTitle", fontSize=13, leading=16, spaceBefore=12, spaceAfter=6, textColor=colors.HexColor("#222222")))
    styles.add(ParagraphStyle(name="Mono", fontName="Courier", fontSize=8, leading=10, backColor=colors.HexColor("#F4F4F4")))

    doc = SimpleDocTemplate(
        str(output_path), pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
    )
    story = []

    story.append(Spacer(1, 5 * cm))
    story.append(Paragraph("Security Assessment Report", styles["Cover"]))
    story.append(Paragraph(target, styles["CoverSub"]))
    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph(f"Date: {generated}", styles["CoverSub"]))
    story.append(Paragraph(f"Tester: {tester}", styles["CoverSub"]))
    story.append(Paragraph("Generated by Prothos", styles["CoverSub"]))
    story.append(PageBreak())

    story.append(Paragraph("Executive Summary", styles["Heading1"]))
    story.append(Paragraph(
        f"This report documents the findings of a security assessment against "
        f"<b>{target}</b>. A total of <b>{len(findings)}</b> findings were identified.",
        styles["BodyText"]))
    story.append(Spacer(1, 0.4 * cm))

    summary_rows = [["Severity", "Count"]]
    for sev in SEVERITY_ORDER:
        summary_rows.append([sev.capitalize(), str(counts[sev])])
    summary_rows.append(["Total", str(len(findings))])

    summary_table = Table(summary_rows, colWidths=[6 * cm, 3 * cm])
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#222222")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#EEEEEE")),
    ]
    for i, sev in enumerate(SEVERITY_ORDER, start=1):
        style_cmds.append(("TEXTCOLOR", (0, i), (0, i), colors.HexColor(SEVERITY_HEX[sev])))
    summary_table.setStyle(TableStyle(style_cmds))
    story.append(summary_table)
    story.append(PageBreak())

    story.append(Paragraph("Technical Findings", styles["Heading1"]))
    for i, f in enumerate(findings, 1):
        sev = f.get("severity", "info")
        title = f.get("title") or f.get("issue") or f.get("module", "finding")
        story.append(Paragraph(
            f'<font color="{SEVERITY_HEX.get(sev, "#000000")}">[{sev.upper()}]</font> '
            f"{i}. {title}", styles["FindingTitle"]))

        meta_rows = [
            ["Severity", sev],
            ["CVSS (est.)", str(SEVERITY_CVSS.get(sev, 0.0))],
            ["Module", f.get("module", "-")],
            ["Location", str(f.get("url") or f.get("target") or "-")],
        ]
        if f.get("param"):
            meta_rows.append(["Parameter", str(f.get("param"))])
        if f.get("cve"):
            meta_rows.append(["CVE", str(f.get("cve"))])
        meta_table = Table(meta_rows, colWidths=[4 * cm, 12 * cm])
        meta_table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F4F4F4")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.2 * cm))

        if f.get("description"):
            story.append(Paragraph("<b>Description</b>", styles["BodyText"]))
            story.append(Paragraph(str(f.get("description"))[:1500], styles["BodyText"]))
        if f.get("payload"):
            story.append(Paragraph("<b>Proof of Concept</b>", styles["BodyText"]))
            story.append(Paragraph(str(f.get("payload"))[:800].replace("<", "&lt;").replace(">", "&gt;"), styles["Mono"]))
        if f.get("evidence"):
            story.append(Paragraph("<b>Evidence</b>", styles["BodyText"]))
            story.append(Paragraph(str(f.get("evidence"))[:800].replace("<", "&lt;").replace(">", "&gt;"), styles["Mono"]))
        story.append(Paragraph("<b>Remediation</b>", styles["BodyText"]))
        story.append(Paragraph(
            str(f.get("remediation") or "Review and remediate per OWASP guidance."),
            styles["BodyText"]))
        story.append(Spacer(1, 0.3 * cm))

    story.append(PageBreak())
    story.append(Paragraph("Remediation Roadmap", styles["Heading1"]))
    for sev in SEVERITY_ORDER:
        if counts[sev]:
            story.append(Paragraph(
                f'<font color="{SEVERITY_HEX[sev]}"><b>{sev.capitalize()} ({counts[sev]})</b></font>: '
                f"{REMEDIATION_ROADMAP[sev]}", styles["BodyText"]))
            story.append(Spacer(1, 0.2 * cm))

    doc.build(story)
    return True


def run_pdf_report(session: Any, output_path: str, tester: str = "Prothos") -> str:
    data = _as_dict(session)
    findings = _findings(data)
    console.print(f"\n[bold red][*][/bold red] PDF report → [bold white]{output_path}[/bold white]")
    console.print(f"[dim]    Findings: {len(findings)}[/dim]")

    try:
        ok = _build_pdf(data, output_path, tester)
        if not ok:
            console.print("[red][!] reportlab not installed — run: pip install reportlab[/red]")
            return output_path
        console.print(f"[dim][+] Saved to {output_path}[/dim]")
    except Exception as e:
        console.print(f"[red][!] Failed to build PDF: {e}[/red]")

    return output_path
